steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'asia.gcr.io/$REPO_NAME:$RELEASE_VERSION', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'asia.gcr.io/$REPO_NAME:$RELEASE_VERSION']

- name: 'gcr.io/cloud-builders/gcloud'
  id : Deploy to Cloud Run
  args: ['run', 'deploy', 'healthy-salad', '--image', 'asia.gcr.io/$REPO_NAME:$RELEASE_VERSION', '--region', 
          'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']
